### ISSUE TITLE
ckpool/Kano was added 2 months ago but blockchain still doesn't display it

### ISSUE THREAD

**Issue by kanoi** [blockchain/Blockchain-Known-Pools#20]
https://github.com/blockchain/Blockchain-Known-Pools/blob/master/pools.json#L147

last 2 blocks:
https://blockchain.info/block-index/532268/0000000000000000114e4f72465cf903bcb22075c2e3f386af6db9d7fdc0a88f
https://blockchain.info/block-index/532257/000000000000000015eced7801449ca23e12c301172c51e8473f494f6f2bb1bc

**Comment by jameshilliard** [comment]
Any reason this still isn't showing up? This pool is bigger than eclipse and bitminter. The block history can be seen on this page https://www.kano.is/index.php?k=pblocks .

**Comment by kanoi** [comment]
The original commit didn't include the 0x05 byte between "ckpool" and "/Kano"
Hopefully this pull will fix it :p
https://github.com/blockchain/Blockchain-Known-Pools/pull/28

**Comment by rubensayshi** [comment]
yea, we use "/Kano" to detect it and works just fine; https://www.blocktrail.com/BTC/pool/kano

**Comment by jameshilliard** [comment]
Looks like that worked.
https://blockchain.info/blocks/Kano%20CKPool
