### ISSUE TITLE
Bitcoin India link shows "No Blocks Found"

### ISSUE THREAD

**Issue by jameshilliard** [blockchain/Blockchain-Known-Pools#96]
Bitcoin India shows up [here](https://blockchain.info/pools) but when you click the [link](https://blockchain.info/blocks/Bitcoin%20India) it says "No Blocks Found".

**Comment by alecalve** [comment]
Linking to the discussion in #97 https://github.com/blockchain/Blockchain-Known-Pools/pull/97#issuecomment-263220795

**Comment by jameshilliard** [comment]
@alecalve closing this as it appears fixed
